use super::{
    Descriptor, JSON, NONE, REDACTED_NAME, RawKind, descriptor, descriptor_with_conflicts,
};

const SETUP_FLAGS: &[&str] = &[
    "--yes",
    "--no-interactive",
    "--service",
    "--no-service",
    "--skip-runtime",
    "--verbose",
];
const UNINSTALL_FLAGS: &[&str] = &[
    "--dry-run",
    "--yes",
    "--keep-cache",
    "--keep-service-files",
    "--purge-config",
    "--keep-config",
    "--json",
    "--verbose",
];
const MODEL_PREPARE_FLAGS: &[&str] = &[
    "--dry-run",
    "--confirm",
    "--follow",
    "--json",
    "--list",
    "--update-script",
];
const SETUP_CONFLICTS: &[&[&str]] = &[&["--service", "--no-service"]];
const UNINSTALL_CONFLICTS: &[&[&str]] = &[&["--purge-config", "--keep-config"]];
const UPDATE_CONFLICTS: &[&[&str]] = &[&["--flavor", "--detect-flavor"]];
const SKILLS_INSTALL_CONFLICTS: &[&[&str]] = &[&["--agent", "--all"]];

pub(super) const DESCRIPTORS: &[Descriptor] = &[
    descriptor_with_conflicts(
        &["mesh-llm", "setup"],
        SETUP_FLAGS,
        NONE,
        SETUP_CONFLICTS,
        false,
        RawKind::None,
    ),
    descriptor_with_conflicts(
        &["mesh-llm", "uninstall"],
        UNINSTALL_FLAGS,
        &["--binary-path"],
        UNINSTALL_CONFLICTS,
        false,
        RawKind::None,
    ),
    descriptor(
        &["mesh-llm", "download"],
        &["--draft"],
        &["name"],
        false,
        RawKind::None,
    ),
    descriptor_with_conflicts(
        &["mesh-llm", "update"],
        &["--detect-flavor"],
        &["--version", "--flavor"],
        UPDATE_CONFLICTS,
        false,
        RawKind::None,
    ),
    descriptor(&["mesh-llm", "status"], NONE, NONE, true, RawKind::None),
    descriptor(
        &["mesh-llm", "load"],
        NONE,
        REDACTED_NAME,
        true,
        RawKind::None,
    ),
    descriptor(
        &["mesh-llm", "unload"],
        NONE,
        REDACTED_NAME,
        true,
        RawKind::None,
    ),
    descriptor(
        &["mesh-llm", "discover"],
        &["--auto"],
        &["--name", "--model", "--min-vram", "--region", "--relay"],
        false,
        RawKind::None,
    ),
    descriptor(
        &["mesh-llm", "rotate-key"],
        NONE,
        NONE,
        false,
        RawKind::None,
    ),
    descriptor(
        &["mesh-llm", "goose"],
        NONE,
        &["--model"],
        true,
        RawKind::None,
    ),
    descriptor(
        &["mesh-llm", "claude"],
        NONE,
        &["--model"],
        true,
        RawKind::None,
    ),
    descriptor(
        &["mesh-llm", "pi"],
        &["--write"],
        &["--model", "--host"],
        false,
        RawKind::None,
    ),
    descriptor(
        &["mesh-llm", "opencode"],
        &["--write"],
        &["--model", "--host"],
        false,
        RawKind::None,
    ),
    descriptor(&["mesh-llm", "stop"], NONE, NONE, false, RawKind::None),
    descriptor(
        &["mesh-llm", "external-plugin"],
        NONE,
        &["argv"],
        false,
        RawKind::None,
    ),
    descriptor(
        &["mesh-llm", "model-prepare"],
        MODEL_PREPARE_FLAGS,
        &[
            "source_repo",
            "--quant",
            "--target",
            "--model-id",
            "--flavor",
            "--timeout",
            "--mesh-llm-ref",
            "--status",
            "--logs",
            "--cancel",
        ],
        false,
        RawKind::None,
    ),
    descriptor(&["mesh-llm", "gpus"], JSON, NONE, false, RawKind::None),
    descriptor(
        &["mesh-llm", "gpus", "detect"],
        JSON,
        NONE,
        false,
        RawKind::None,
    ),
    descriptor(
        &["mesh-llm", "gpus", "run-benchmark"],
        JSON,
        NONE,
        false,
        RawKind::Backend,
    ),
    descriptor(
        &["mesh-llm", "config", "validate"],
        JSON,
        &["--config-path"],
        false,
        RawKind::None,
    ),
    descriptor(&["mesh-llm", "doctor"], JSON, NONE, false, RawKind::None),
    descriptor(
        &["mesh-llm", "doctor", "split"],
        JSON,
        &["--model-ref", "--output-dir"],
        true,
        RawKind::None,
    ),
    descriptor_with_conflicts(
        &["mesh-llm", "skills", "install"],
        &["--all", "--dry-run", "--force"],
        &["--agent"],
        SKILLS_INSTALL_CONFLICTS,
        false,
        RawKind::None,
    ),
];
