[package]
name = "model-resolver"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Model reference resolution helpers for mesh-llm"
repository = "https://github.com/Mesh-LLM/mesh-llm"
homepage = "https://github.com/Mesh-LLM/mesh-llm"
readme = "README.md"

[dependencies]
anyhow.workspace = true
model-ref = { path = "../model-ref", version = "0.76.0-rc8"  }
model-artifact = { path = "../model-artifact", version = "0.76.0-rc8"  }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3"
