pub mod activity;
pub mod autoupdate;
pub mod backend;
pub mod benchmark;
pub mod benchmark_prompts;
pub use mesh_llm_release_footer as embedded_release_footer;
pub mod hardware;
pub mod process;
pub mod release_target;
pub mod util;
pub mod vram;
